name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  flutter_riverpod: ^3.0.0
  firebase_core: ^4.1.0
  google_fonts: ^6.3.1
  get: ^4.7.2
  firebase_auth: ^6.0.2
  intl: ^0.20.2
  table_calendar: ^3.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/health_1.png
    - assets/images/lifeline.png
    - assets/images/spinal.png
    - assets/images/anatomy.png
    - assets/images/document.png
    - assets/images/heart.png
    - assets/images/back.png
    - assets/images/challenge.png
    - assets/images/logo.png
    - assets/images/group.png